import { Metadata } from "next"

export const metadata: Metadata = {
  title:{
    absolute:'',
    default:'',
    template: '%s | NextJS'
  },
  description: 'Generated by Next.js',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header>
        <p>Header</p>
      </header>
      <body>{children}</body>
      <footer>
        <p>Footer</p>
      </footer>
    </html>
  )
}
