export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header>
        <p>Header</p>
      </header>
      <body>{children}</body>
      <footer>
        <p>Footer</p>
      </footer>
    </html>
  )
}
